### ISSUE TITLE
"yemeden" word is analyzed as unknown

### ISSUE THREAD

**Issue by adilyildiz** [ahmetaa/zemberek-nlp#225] opened 2019-06-14 07:02 UTC
"fırçalamadan" is analyzed as "fırçala:Verb|/madan:WithoutHavingDoneSo→Adv"

but not "yemeden" word. It has to be same.

**Comment by ahmetaa** [comment] 2019-06-15 20:34
I cannot reproduce it in current trunk version. What is the version you are using?

```
yemeden
[yemek:Verb] ye:Verb|meden:WithoutHavingDoneSo→Adv
[yemek:Verb] ye:Verb|me:Inf2→Noun+A3sg+den:Abl
```

**Comment by ahmetaa** [comment] 2019-06-15 20:35
Perhaps it is because what you see is the result of disambiguator, which probably makes a mistake there.

**Comment by adilyildiz** [comment] 2019-06-15 20:44
"Dedem, yemek yemeden gitti." example sentence. I am using 0.17 in drive distro folder.

**Comment by adilyildiz** [comment] 2019-06-15 20:45
But not only in sentence when i send "yemeden." as only input it gives UNK

**Comment by ahmetaa** [comment] 2019-06-16 17:01
can you show a minimal example for reproducing the issue?

**Comment by adilyildiz** [comment] 2019-06-17 08:19
`import java.io.IOException;
import java.util.List;

import zemberek.core.logging.Log;
import zemberek.morphology.analysis.SentenceAnalysis;
import zemberek.morphology.analysis.SentenceWordAnalysis;
import zemberek.morphology.analysis.WordAnalysis;
import zemberek.morphology.lexicon.RootLexicon;
import zemberek.morphology.TurkishMorphology;
import zemberek.tokenization.TurkishSentenceExtractor;
public class zp {
	
	public static void kontrolet(String tur,String metin) throws IOException {
		TurkishMorphology morphology = TurkishMorphology.builder()        
			    .setLexicon(RootLexicon.getDefault())
			    .useInformalAnalysis()
			    .build();
		TurkishSentenceExtractor extractor = TurkishSentenceExtractor.DEFAULT;
       String gelenkelime=""; 
        List<String> sentences = extractor.fromParagraph(metin);
	            for (String sentence : sentences) {
	            	List<WordAnalysis> s=morphology.analyzeSentence(sentence);
	            	SentenceAnalysis result = morphology.disambiguate(sentence, s);
	            	
	                for (SentenceWordAnalysis r:result){
	                	gelenkelime=r.getWordAnalysis().getInput();
	                	System.out.print(gelenkelime);
                		System.out.print(r.getBestAnalysis());
                		System.out.print("##");	
                		
	                	System.out.println();
	                	
	                }

	            }
	}
	 public static void main(String[] args) throws IOException {
	        // TODO code application logic here
		 String input1,input2;
		 Log.setError();
		    try {
		         input1 = args[0];
		         input2=args[1];
		         kontrolet(input1,input2);
		        }
		    catch (ArrayIndexOutOfBoundsException e){
		    	input2 = "Dedem, yemek yemeden gitti.";
		         input1="tek";
		         kontrolet(input1,input2);
		    }
	    }
}
`

`Dedem[dede:Noun] dede:Noun+A3sg+m:P1sg##
,[,:Punc] ,:Punc##
yemek[yemek:Noun] yemek:Noun+A3sg##
yemeden[UNK:Unk,Unk] yemeden:Unknown##
gitti[gitmek:Verb] git:Verb+ti:Past+A3sg##
.[.:Punc] .:Punc##`

**Comment by adilyildiz** [comment] 2019-06-17 08:32
0.16 => `TurkishMorphology morphology = TurkishMorphology.createWithDefaults();` is working ok.
0.17 => ```
TurkishMorphology morphology = TurkishMorphology.builder()        
			    .setLexicon(RootLexicon.getDefault())
			    .useInformalAnalysis()
			    .build();
``` not working

**Comment by ahmetaa** [comment] 2019-07-23 12:01
0.17.1 ile test edebilir misiniz?

**Comment by adilyildiz** [comment] 2019-07-29 08:10
> 0.17.1 ile test edebilir misiniz?

hala düzgün parçalayamıyor birşey değişmedi. 0.16 ile çalışıyor hala.

**Comment by ahmetaa** [comment] 2019-10-02 06:22
Your exact same code generates this output:

```
Dedem[dede:Noun] dede:Noun+A3sg+m:P1sg##
,[,:Punc] ,:Punc##
yemek[yemek:Noun] yemek:Noun+A3sg##
yemeden[yemek:Verb] ye:Verb|meden:WithoutHavingDoneSo→Adv##
gitti[gitmek:Verb] git:Verb+ti:Past+A3sg##
.[.:Punc] .:Punc##
```

I cannot reproduce the problem, so closing the issue.

**Closed by ahmetaa** 2019-10-02 06:22 UTC
